FROM golang
RUN go get -u github.com/golang/dep/cmd/dep
RUN go env
ADD . /go/src/{{.ProjectPath}}
WORKDIR /go/src/{{.ProjectPath}}
RUN make clean
RUN make
CMD /go/src/{{.ProjectPath}}/bin/{{.DockerImage}}
